// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.iChromeActions")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.iGeneral._sleepInterval")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.iGeneral")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.iMsEdgeActions")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.interfaces.iGeneral._sleepInterval")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.interfaces.iChromeActions")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.interfaces.iGeneral")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.interfaces.iMsEdgeActions")]
[assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.GeneralActions.GetPixelsToMove(OpenQA.Selenium.IWebElement,System.Decimal,System.Decimal,System.Decimal)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.GeneralActions.GetPixelsToMove(OpenQA.Selenium.IWebElement,System.Decimal,System.Decimal,System.Decimal)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0075:Simplify conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.GeneralActions.RunBatchCommands(System.Collections.Generic.List{BurnSoft.Testing.Web.Selenium.Types.BatchCommandList},System.String@)~System.Collections.Generic.List{BurnSoft.Testing.Web.Selenium.Types.BatchCommandList}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.FlexAction._sleepInterval")]
[assembly: SuppressMessage("CodeQuality", "IDE0076:Invalid global 'SuppressMessageAttribute'", Justification = "<Pending>")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:BurnSoft.Testing.Web.Selenium.interfaces.iIEActions")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.SeleniumIde.RunSeleniumIdeFile(BurnSoft.Testing.Web.Selenium.FlexAction.UseDriver,System.String,System.String,System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.command")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.comment")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.id")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.target")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.targets")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Command.value")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.id")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.plugins")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.suites")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.tests")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.url")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.urls")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.SideFile.version")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.id")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.parallel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.persistSession")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.tests")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Suite.timeout")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Test.commands")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Test.id")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BurnSoft.Testing.Web.Selenium.Types.Test.name")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.BatchCmdHelper.GetLinkAndGoTo(System.String,System.String)~System.Collections.Generic.List{BurnSoft.Testing.Web.Selenium.Types.BatchCommandList}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.BatchCmdHelper.Sleep(System.Int32)~System.Collections.Generic.List{BurnSoft.Testing.Web.Selenium.Types.BatchCommandList}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:BurnSoft.Testing.Web.Selenium.BatchCmdHelper.Sleep500~System.Collections.Generic.List{BurnSoft.Testing.Web.Selenium.Types.BatchCommandList}")]
